---
- name: install clang
  hosts: development_hosts
  become: yes
  roles:
     - role: ansiblebit.oracle-java
       oracle_java_set_as_default: yes

  vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Enter password"
    private: yes

  tasks:
  - name: install clang
    apt: name=clang state=latest

  - name: install clang-format
    apt: name=clang-format state=latest

  - name: install clang-tidy
    apt: name=clang-tidy state=latest

  - name: install libclang1
    apt: name=libclang1 state=latest

  - name: install lldb
    apt: name=lldb state=latest

  - name: install llvm
    apt: name=llvm state=latest

  - name: install llvm-dev
    apt: name=llvm-dev state=latest

  - name: install llvm-runtime
    apt: name=llvm-runtime state=latest

  - name: install cmake
    apt: name=cmake state=latest

  - name: install emacs
    apt: name=emacs state=latest

  - name: install gvim
    apt: name=vim state=latest

  - name: add apt key for nodesource
    apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

  - name: add repo for nodesource
    apt_repository:
          repo: 'deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main'
          update_cache: yes

  - name: install nodejs
    apt: name=nodejs

  - name: install aptitude
    apt: name=aptitude state=latest

  - name: add Atom repo
    apt_repository: repo=ppa:webupd8team/atom

  - name: update packages
    apt: upgrade=full

  - name: install atom
    apt: name=atom state=latest

  - name: add Oracle JDK repo
    apt_repository: repo=ppa:webupd8team/java

  - name: Update packages
    apt: upgrade=full

  - name: install maven
    apt: name=maven state=latest
